### ISSUE TITLE
Wrong version test

### ISSUE THREAD

**Issue by benjamw** [TheRemote/RaspberryPiMinecraft#11]
https://github.com/TheRemote/RaspberryPiMinecraft/blob/efbdb15db6049507d05605e23e2b83b34efb47ab/SetupMinecraft.sh#L151

This checks for version 13, then tries to install version 14.

It then checks for 13 again, and tries to install 13. So I'm guessing the first check should be for version 14.

**Comment by TheRemote** [comment]
Doh!  You're absolutely right.  I was trying to get ahead of OpenJDK's aggressive release schedule and flubbed my copy paste.

This has now been fixed!
