### ISSUE TITLE
Update for Ubuntu Server 19.10 please.

### ISSUE THREAD

**Issue by AKoskovich** [TheRemote/RaspberryPiMinecraft#15]
Appears the only thing that needs to be changed for 19.10 is the JDK, says the default is 58(?) after downloading OpenJDK 11 (not headless) and setting it as default it ran fine.

**Comment by TheRemote** [comment]
This is tricky because it could cause problems if the script changes the default options.  However I have added a whole section on using update-alternatives to address this.  Thanks!
