### ISSUE TITLE
[Question] Install somewhere other than home dir

### ISSUE THREAD

**Issue by Minecraftschurli** [TheRemote/RaspberryPiMinecraft#19]
What would I need to change in the installation script to install it with its own user "minecraft" in /var/lib/minecraft like other applications do it?

**Comment by TheRemote** [comment]
Hey Minecraftschurli,

All you would need to do is open up SetupMinecraft.sh and if you do a Ctrl+F (or a Ctrl+W for searching with nano) and search for the "~" symbol.  That represents the home directory.  There is a DirName=$(readlinke -e ~) that is particularly important.  If you change those it should take care of it for you!
