### ISSUE TITLE
Great script and great guide ! Do you plan to add Fabric mods compatibility to your script ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [TheRemote/RaspberryPiMinecraft#22]
Hi,

I absolutely love your work on this script, it allowed me to make a nice server always running for friends, it is perfect for noobs but also highly configurable and your tutorial is perfect. You're doing an amazing job !!!

But I was thinking about Fabric, and how Lithium/Sodium/Phosphor allow greater performances. That would be nice on Raspberry, server side. Do you think it would be possible to add Fabric mods compatibility on the script ?

Thanks in advance for your answer and thanks for your incredible work ! Have a great day

**Comment by TheRemote** [comment]
That's a great question.  I know it has been a while.  I don't believe it's possible to run Fabric mods in Spigot but I believe it is possible to run Spigot mods on a Fabric server using Cardboard.

If anyone knows of a way definitely let us know!

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> That's a great question. I know it has been a while. I don't believe it's possible to run Fabric mods in Spigot but I believe it is possible to run Spigot mods on a Fabric server using Cardboard.
> 
> If anyone knows of a way definitely let us know!

Thanks for your answer ! I just looked at Cardboard, and it looks very interesting. But as it works on a Fabric server and not on a Paper server, I guess it would be complicated to run on a Raspberry ? Paper is probably much more efficient than fabric server. Did you try fabric on Rpi ?
Having Fabric compatibility on my pi would be incredible to add quest mods, creatures, blocks... that's probably the next stage.
(I'll probably try it too)
