### ISSUE TITLE
Plans for Bedrock Edition?

### ISSUE THREAD

**Issue by capsload2** [TheRemote/RaspberryPiMinecraft#23]
Hey man,

excellent work on your Raspberry Script.

Are there any plans of a Bedrock Edition as well?

**Comment by TheRemote** [comment]
Hey capsload,

I did do one for bedrock [here but it was very slow](https://jamesachambers.com/official-minecraft-bedrock-dedicated-server-on-raspberry-pi/).  I haven't tried again with the new Pi yet!
