### ISSUE TITLE
"Enter amount of memory"-text: add "M" in example

### ISSUE THREAD

**Issue by Coernel82** [TheRemote/RaspberryPiMinecraft#33]
The text:
`Enter amount of memory in megabytes to dedicate to the Minecraft server (recommended: 511)`
suggest to enter `511` however you have to enter `511M`. Though this might be common knowlege to advanced users this may confuse beginners.
So change the "recommended" text from "recommended: x" to "recommended: xM"

**Comment by TheRemote** [comment]
It puts the M for you.  You do not have to do this, nor should you.  It's probably why the rest of your script was so broken to be honest with you.

screen -dmS minecraft java -jar -Xms400M -XmxmemselectM dirname/minecraft/paperclip.jar

That's the template that gets replaced.  memselect gets replaced by sed.  Notice how it has an M after it.  If you add this yourself you will have 2 Ms which is probably why your server didn't start.

They are templates that replace values in the scripts with what you use during SetupMinecraft.sh.  It's literally meant for people to just run and select some basic values and that's it.  This is way overthinking it to the point where you're introducing unexpected input that is going to break it (and did from what I can see).  Literally if you left everything as the defaults and started it then it would work as intended basically.
