### ISSUE TITLE
Does not pull latest paper version

### ISSUE THREAD

**Issue by Meganium97** [TheRemote/RaspberryPiMinecraft#41]
Not sure what exactly the problem is. It claims it does but it ends up being stuck on update 0 and the server complains about my version being 18 versions behind.

**Comment by TheRemote** [comment]
Hello,

Thanks for reporting this!  I just made a change to fix it.  Can you run update.sh or SetupMinecraft.sh again to update to the latest scripts and make sure that got it for you?

Thanks!
