### ISSUE TITLE
Setting up the script gives a error.

### ISSUE THREAD

**Issue by Squawkykaka** [TheRemote/RaspberryPiMinecraft#43]
When I run the script and get to the 'Choose if you want daily reboot section' it gives a error
Setting server file permissions...
tail: cannot open '' for reading: No such file or directory
Then:
Setup is complete.  Starting Minecraft server...
Must be connected to a terminal.
Must be connected to a terminal.
If I continue after this and run the start.sh script it doesn't turn the server on.
Is there any way I could fix that?
Thanks Squawkykaka

**Comment by TheRemote** [comment]
I'd need to see more.  I can fix that tail error but it doesn't tell us what is going wrong.  What do you get when you run start.sh?

**Comment by Squawkykaka** [comment]
This is what it says:
pi@raspberrypi:~/minecraft $ ./start.sh
Updating to most recent paperclip version ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   183  100   183    0     0    855      0 --:--:-- --:--:-- --:--:--   859
Latest paperclip build found: 138
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36.4M  100 36.4M    0     0  21.9M      0  0:00:01  0:00:01 --:--:-- 22.0M\Starting Minecraft server.  To view window type screen -r minecraft.
To minimize the window and let the server run in the background, press Ctrl+A then Ctrl+D
pi@raspberrypi:~/minecraft $ screen -r minecraft
There is no screen to be resumed matching minecraft.

(Sorry for the lines)

**Comment by TheRemote** [comment]
No worries, everything looks in order there.  We probably need to look at the log files which are in the "logs" directory.  latest.log or one of the later date ones should tell us what it is here!

**Comment by TheRemote** [comment]
Yeah that definitely does tend to happen.  I'm sure the logs revealed the problem here but if not let me know and I can help further!

**Comment by Squawkykaka** [comment]
this is the latest.log file everything seems in check but i cant be sure:
[16:58:39] [ServerMain/INFO]: Building unoptimized datafixer
[16:58:44] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:58:44] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[16:58:55] [ServerMain/INFO]: Loaded 7 recipes

**Comment by Squawkykaka** [comment]
I di update to a 64 Bit machine but the same error occurs:
Automatically reboot Pi and update server at 4am daily (y/n)?y
no crontab for pi
Daily reboot scheduled.  To change time or remove automatic reboot type crontab -e
Setting server file permissions...
Setup is complete.  Starting Minecraft server...
Must be connected to a terminal.
Must be connected to a terminal.

**Comment by Squawkykaka** [comment]
Oh apologies it seems to be running with the error still occurring?

**Comment by TheRemote** [comment]
No worries at all!  It should be running yes.  You can reattach with screen -r and it should pull up the server console for you!
