### ISSUE TITLE
Feature suggestion/fork suggestion: Forge version?

### ISSUE THREAD

**Issue by Meganium97** [TheRemote/RaspberryPiMinecraft#44]
Do you think this could be modified to set up a forge server? I like the idea for paper, I just want to be able to run mods instead of just being stuck with plugins.

**Comment by TheRemote** [comment]
I'm absolutely open to this.  It would most likely be a containerized version.  I believe people have actually modified this into Forge before but I'm not sure if anyone has shared the code publically.

I will definitely update this when something is out related to Forge!
