### ISSUE TITLE
Version 1.19.3

### ISSUE THREAD

**Issue by Atten007** [TheRemote/RaspberryPiMinecraft#45]
Hi,

I wanted to set up another PaperMC server with your script, but yesterday’s version 1.19.3 is still missing. Can you add it?

Anyways, you have a good script, which I like to use again and again for new servers. Please still keep it up!

Greetings,
Atten 😊

**Comment by TheRemote** [comment]
This doesn't exist yet.  The server uses the Paper Minecraft server.

The downloads page is available here:  https://papermc.io/downloads

There is no Paper 1.19.3 yet.  Once you see it available on the page we can update!

**Comment by Atten007** [comment]
@TheRemote the first experimental builds for PaperMC 1.19.3 are now out here: https://papermc.io/downloads

**Comment by TheRemote** [comment]
Thanks for the heads up, I've got this released!

Enjoy and take care!
