### ISSUE TITLE
1.19.4 support?

### ISSUE THREAD

**Issue by Atten007** [TheRemote/RaspberryPiMinecraft#47]
Hello,

The new Minecraft 1.19.4 version has been released on Tuesday and it's now also available for PaperMC. Unfortunately, your script hasn't currently 1.19.4 support, so I wanted to ask you: "is it possible to update your script to 1.19.4"?

Best regards,
Atten 😄

**Comment by TheRemote** [comment]
Sure!  This wasn't up when I checked literally a couple of hours ago. 

Make backups.  Here's the warning from Paper's site:

`Builds marked in red are early, experimental builds. They are only recommended for usage on test servers and should be used with caution. Backups are mandatory!`

In other words if there's any bugs your server will die.  Permanently.  Will it happen?  Probably not but it does sometimes so you have to be prepared with a backup.

For people who might not want to deal with risking this it's best to wait a day or two until the builds are marked stable.  For anyone who really wants to use the new features though just make sure you have backups in case things go horribly wrong.  

Hopefully that helps!

**Comment by Atten007** [comment]
Yes, I'll make a backup with my server!

**Comment by TheRemote** [comment]
Excellent, I just pushed the update now so if you run SetupMinecraft.sh again it should pull the latest version for you!

**Comment by Atten007** [comment]
Ok, thx! 😊
