### ISSUE TITLE
Extra Setup

### ISSUE THREAD

**Issue by actraiser30** [TheRemote/RaspberryPiMinecraft#5]
Hello great script is it possible to add the NoSpawnChunks.jar plugin to the script to be installed automatically to the server?

http://ci.dmulloy2.net/job/NoSpawnChunks/

and also is it possible to make a second script to install the normal minecraft server not the paperclip?

or i just replace the links in your script eg:https://ci.destroystokyo.com/job/PaperSpigot/lastSuccessfulBuild/artifact/paperclip.jar

to donwload the normal spigot-1.13.1.jar ?

Thanks

**Comment by mtoensing** [comment]
From my experience more plugins are not better on this minimalistic setup. 

And personally I so no reason to switch from paper to spigot. Paper is in every aspect superior compared to spigot. Especially on a raspberry pi with limited ressources.
