### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 456dev** [TheRemote/RaspberryPiMinecraft#6]
Use aikars Java flags in start.sh

https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

**Comment by mtoensing** [comment]
I tried this on a RPi3b+:

`java -Xms800MB -Xmx800MB -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs
`
Result was this: 
![image](https://user-images.githubusercontent.com/136737/47701328-be4fe400-dc19-11e8-86f2-a8ab18d29c11.png)

System became unresponsive within 5 minutes without anyone online. Maybe some parameters can be changed to avoid this but out of the box it does not work.

This is the normal workload with default settings by @TheRemote 

![image](https://user-images.githubusercontent.com/136737/47701622-b47ab080-dc1a-11e8-80e0-071dc07a7175.png)

**Comment by 456dev** [comment]
Hmm. Ok I'll close it then.
