### ISSUE TITLE
dpkg wrong

### ISSUE THREAD

**Issue by sks-lab** [TheRemote/RaspberryPiMinecraft#8]
always get this error message
![Unbenannt](https://user-images.githubusercontent.com/52048618/59871407-cec6f180-9397-11e9-8091-25be7d34b121.PNG)

**Comment by Atompapst** [comment]
Hey, 
try: `sudo apt --fix-broken install`
when finished restart: `sudo reboot`
then run `./SetupMinecraft.sh` again.

**Comment by TheRemote** [comment]
Chris's comment is correct.  The command resolves package conflicts between the latest OpenJDK and other older or alternative Java installations so the new OpenJDK installation can go through.
